---
title: "What to do about missing values"
author: "Ahnaf Alam"
format:
  pdf:
    toc: true
    number-sections: true
date: today
date-format: long
bibliography: cite.bib
---

# General idea

Missing data points are a regular feature in almost all datasets. The defining task for researchers is figure out the source of the missing data as these can lead to bias and error [@newman2014missing]. Missing data can arise for many reasons, however, we can categorize missing values into three distinct categories:

  * Missing completely at random (MCAR)
  * Missing at random (MAR)
  * Missing not at random (MNAR)

The subsequent paragraph will focus in discussion what these categories of missing values, their features, reasons and what can researchers do to mitigate the issue of missing data.

# Missing completely at random

This situation arises when data points are missing independent of any other variables [@Alexander_2023]. In layman's terms, this points to a situation when data points are missing at random and it is not related to any other factors or variables in the data set. This coincidental situation implies the data set in hand, is still representative of the broader population. Amongst the categories of missing data, this form of missing data is the only one that is completely random. However, this form of missing data is also extremely rare as this type of data requires reserchers to make "untenable assumptions" [@graham2009missing]. 

# Missing at random

MAR differentiates from MCAR in that missing values are related to one of the of the other variables in the data set. Take for example, a situation where a researcher is interested in differing Indian caste system's opinion on country's current federal government. In this situation, we will have MCAR, if we have missing values for opinion variable for lower castes compared to higher castes.  MAR is systematic missing data mechanism [@newman2014missing], unlike MCAR. 

# Missing not at random

MCAR occurs when missing data is related to unobserved or latent variable or that missing data is related to the missing variable itself. Suppose you are collecting data on patients weights in a medical clinic. You ask patients to self-report their weight to researcher every two weeks. Now, imagine individuals with higher weight level may feel insecure to share their weight details and therefore, they may not report their weight on a regular basis. In this situation, higher weights is related to missing data for weight. It is often impossible to determine if data is MNAR or not as this requires researcher to compare observed values to missing values and researcher does not have access to missing values [@newman2014missing]. 

# What to do about missing data

There are five common ways to deal with missing values in data sets [@newman2014missing]. They are:

1. Listwise deletion
2. Pairwise deletion
3. Single imputation
4. Maximum likelihood
5. Multiple imputation


## Listwise deletion

The basic idea behind listwise deletion is to delete all cases where data is missing and proceed with the analysis. The obvious issue with this type of mechanism is we risk reducing sample size significantly, especially if there's a lot of missing data points. This is bad as lowering count of observations means the power for statistical tests significance, and this could lead to biased estimate, particularly for MAR and MNAR.

## Pairwise deletion

Pairwise deletion omits data based on variables used in the analysis. In other words, analysis may be completed based on subset of data depending on where the missing value is [@Moran_2024]. For example, if person X has missing data for income, however, has complete data for race, height and weight, then X will be included in all analysis that involves race, height and weight but excluded from analysis that includes income. This, again, could lead to biased estimate, espcially for MAR and MNAR.

## Single imputation

Single imputation involves filling in the missing value using some form of estimate, usually being mean, median or mode. However, doing this leads to underestimation of variance and this methods ignores relationship with other variables [@zhang2016missing]. 


## Maximum likelihood















\newpage
# Citations


